package eu.dapaas.db.dynamo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "DS_CONTENT")
public class DynamoDSContent {
  /*
   * " ID    INTEGER PRIMARY KEY, " + // " DS_ID TEXT NOT NULL, " + //
   * " CHART CHAR(100) NOT NULL, " + // " QUERY TEXT NOT NULL, " + //
   * " TITLE TEXT NOT NULL, " + // " DESCRIPTION TEXT NULL, " + //
   * " SUMMARY TEXT NULL, " + // " DATE_PATTERN CHAR(100) NULL, " + //
   * " ACCESS_URL TEXT NOT NULL " +
   */
  @DynamoDBHashKey(attributeName = "ID")
  @DynamoDBAutoGeneratedKey
  private String id;
  
  @DynamoDBAttribute(attributeName = "DS_ID")
  private String dsId;
  
  @DynamoDBAttribute(attributeName = "CHART")
  private String chart;
  
  @DynamoDBAttribute(attributeName = "QUERY")
  private String query;
  
  @DynamoDBAttribute(attributeName = "TITLE")
  private String title;
  
  @DynamoDBAttribute(attributeName = "DESCRIPTION")
  private String description;
  
  @DynamoDBAttribute(attributeName = "SUMMARY")
  private String summary;
  
  @DynamoDBAttribute(attributeName = "DATE_PATTERN")
  private String datePattern;
  
  @DynamoDBAttribute(attributeName = "ACCESS_URL")
  private String accessURL;
  
  @DynamoDBAttribute(attributeName = "POLIGON_ID")
  private String poligonId;
  
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getDsId() {
    return dsId;
  }

  public void setDsId(String dsId) {
    this.dsId = dsId;
  }

  public String getChart() {
    return chart;
  }

  public void setChart(String chart) {
    this.chart = chart;
  }

  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public String getDatePattern() {
    return datePattern;
  }

  public void setDatePattern(String datePattern) {
    this.datePattern = datePattern;
  }

  public String getAccessURL() {
    return accessURL;
  }

  public void setAccessURL(String accessURL) {
    this.accessURL = accessURL;
  }
//
//  public String getPoligonName() {
//    return poligonName;
//  }
//
//  public void setPoligonName(String poligonName) {
//    this.poligonName = poligonName;
//  }
//
//  public String getPoligonFile() {
//    return poligonFile;
//  }
//
//  public void setPoligonFile(String poligonFile) {
//    this.poligonFile = poligonFile;
//  }

  public String getPoligonId() {
    return poligonId;
  }

  public void setPoligonId(String poligonId) {
    this.poligonId = poligonId;
  }
}
