package eu.dapaas.db.dynamo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "DS_POLIGON")
public class DynamoDSPoligon {

  @DynamoDBHashKey(attributeName = "ID")
  @DynamoDBAutoGeneratedKey
  private String id;
  
  @DynamoDBAttribute(attributeName = "TITLE")
  private String title;
  
  @DynamoDBAttribute(attributeName = "FILENAME")
  private String filename;

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }
}
