package eu.dapaas.db.dynamo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "DS_PORTAL")
public class DynamoDSPortal {
  /*
   * " DS_ID," + " PARAM," + " TITLE " +
   */
  // @DynamoDBHashKey(attributeName = "ID")
  // @DynamoDBAutoGeneratedKey
  // private String id;

  @DynamoDBHashKey(attributeName = "DS_ID")
  private String dsId;

  @DynamoDBAttribute(attributeName = "PARAM")
  private String param;

  @DynamoDBAttribute(attributeName = "TITLE")
  private String title;

  public String getDsId() {
    return dsId;
  }

  public void setDsId(String dsId) {
    this.dsId = dsId;
  }

  public String getParam() {
    return param;
  }

  public void setParam(String param) {
    this.param = param;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

}
